apiVersion: v1
kind: Pod
metadata:
  name: matrix-redis-pod
  labels:
    name: matrix-redis-pod
    app: project-matrix

spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379