apiVersion: v1
kind: Service
metadata:
  name: matrix-inventory-manager
  labels:
    name: matrix-inventory-manager-service
    app: project-matrix

spec:
  ports:
  - port: 9003
    targetPort: 9003
  selector:
    name: matrix-inventory-manager-pod
    app: project-matrix