apiVersion: v1
kind: Service
metadata:
  name: matrix-order-dispatcher
  labels:
    name: matrix-order-dispatcher-service
    app: project-matrix

spec:
  ports:
  - port: 9002
    targetPort: 9002
  selector:
    name: matrix-order-dispatcher-pod
    app: project-matrix
