apiVersion: v1
kind: Pod
metadata:
  name: matrix-order-dispatcher-pod
  labels:
    name: matrix-order-dispatcher-pod
    app: project-matrix

spec:
  containers:
    - name: matrix-order-dispatcher
      image: openmatrix2/matrix-order-dispatcher:latest
      ports:
        - containerPort: 9002