apiVersion: v1
kind: Pod
metadata:
  name: matrix-customer-pod
  labels:
    name: matrix-customer-pod
    app: project-matrix

spec:
  containers:
    - name: matrix-customer
      image: openmatrix2/matrix-customer:latest
      ports:
        - containerPort: 9001